---
# tasks file for play
    - name: install httpd on ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: deploy website on ubuntu
      copy:
        src: ./index.html 
        dest: /var/www/html
        owner: root
        group: root
        mode: 0744 
